/* eslint-disable */
// Generated by Wrangler by running `wrangler types test/worker-integration.d.ts -c wrangler.integration.jsonc --env-interface IntegrationEnv --include-runtime=false` (hash: 429f3431fb310bc423071ef2981eba41)
interface __BaseEnv_IntegrationEnv {
	TPAAS_KV: KVNamespace;
	TPAAS_R2: R2Bucket;
	TPAAS_PENDING_R2: R2Bucket;
	API_LIMIT: RateLimit;
	SUBMIT_LIMIT: RateLimit;
	PREVIEW_LIMIT: RateLimit;
	DISCORD_LIMIT: RateLimit;
	ASSETS_BASE_URL: "https://assets.test";
	SUBMIT_BASE_URL: "https://tpaas.test";
	DISCORD_APPLICATION_ID: "test-app-id";
	DISCORD_REVIEW_CHANNEL_ID: "channel-1";
	DISCORD_PUBLIC_KEY: string;
	DISCORD_BOT_TOKEN: string;
	DISCORD_REVIEW_USER_IDS: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("../src/index");
	}
	interface Env extends __BaseEnv_IntegrationEnv {}
}
interface IntegrationEnv extends __BaseEnv_IntegrationEnv {}
